INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT001',' 2 AV 3-38 Z 1, CUILAPA, SANTA ROSA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT002',' 5 AVE EDIFICIO MORZAN LOCAL 4  ZONA 1 RETAHULEU-','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT003',' 6 AV. 5-55 Z 1. MIXCO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT004',' 6 CALLE 2-76 Z 1, AMATITLAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT005',' 6A. CALLE 0-97 Z 2 ALDEA BOCA DEL MONTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT006',' 7A. CALLE 1-05 Z 1, LOCAL B, VILLA CANALES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT007',' BLVD EL FRUTAL 14-00 Z 5, C.C. EL FRUTAL NIVEL 1, LOCAL 22, VILLA NUEVA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT008','0 CALLE 16-20 Z 4, C.C. METROCENTRO LOC. 106, VILLA NUEVA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT009','0 CALLE 16-20 Z 4, C.C. METROCENTRO LOC. 254, VILLA NUEVA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT010','0 CALLE 3-10 Z 4, SUMPANGO, SACATEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT011','0 CALLE, 16-20 ZONA 4 DE VILLA NUEVA,LOCAL 238, CENTRO COMERCIAL METROCENTRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT012','0 CALLE, 16-20 ZONA 4 DE VILLA NUEVA,LOCAL 292, CENTRO COMERCIAL METROCENTRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT013','1 AV. 5-48 C.C PLAZA EL AHORRO LOCAL 6 Z.1 ALDEA BOCA DEL MONTE VILLA CANALES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT014','1 AVENIDA 0-32 ZONA 2, C.C PLAZA SAN LUIS, LOCAL B, SAN SEBASTIAN, CHIQUIMULILLA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT015','1 CALLE 1-05 Z 1, SAN MIGUEL PETAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT016','1 CALLE 2-25 Z.4 C.C. LA MURALLA LOCAL 1, CHIMALTENANGO, CHIMALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT017','1 CALLE 5 AVE. C C LA TRINIDAD LOCAL 38 ZONA 5 REU','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT018','1 RA CALLE 18-83 ZONA 15, SUPERCENTRO VISTA HERMOSA 2, LOCAL 34.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT019','10 AV. 2-31 CHIQUIMULA, CHIQUIMULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT020','10 MA CALLE 13-92, Z.1 DE LA CIUDAD CAPITAL DEL DEPARTAMENTO DE GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT021','11 AV 8-13 Z 18, COL. ATLANTIDA-','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT022','11 AVE 6-33 Z18  COMPLEJO COMERCIAL METATERMINAL DEL NORTE, LOCAL 36  GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT023','11 AVE 6-33 Z18  COMPLEJO COMERCIAL METATERMINAL DEL NORTE, LOCAL 45  GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT024','12 CALLE 0-93 Z 9, C.C. MONTUFAR LOC. 6','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT025','12 CALLE 1-25 ZONA 10, EDIFICIO GEMINIS 10, LOCAL 232, TORRE NORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT026','13 CALLE 4-00 Z 11, LOCAL 3B C.C AGUILAR BATRES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT027','15 AVENIDA Y 1RA CALLE ESQUINA LOTE NO.8 JOCOTALES CHINAUTLA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT028','18 CALLE 6-02, Z.1 GUATEMALA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT029','1ª CALLE 2-64, ZONA 2, SAN JOSE PINULA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT030','1A. AV. Y 2DA. CALLE BARRIO EL PORVENIR TIQUISATE ESCUINTLA ESTABLECIMIENTO NO. 24','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT031','1A. CALLE 0-41, ZONA 1 JALAPA SUCURSAL 70','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT032','1ERA 7-67 Z.2, C.C.PRADERA EXPRESS PALIN, LOCAL 7, BARRIO SAN LUCAS, PALIN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT033','1ERA CALLE 15-20 Z.2 C.C. PLAZA MAGDALENA LOCAL 111, COBAN, ALTA VERAPAZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT034','1ERA CALLE PB ZONA 1, LAS CRUCES, PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT035','1ERA CALLE Y 5TA AV. Z.5 C.C. LA TRINIDAD LOCAL 7','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT036','1RA AVE. 1-40 ZONA  3 C.C. PRADERA LOCAL  5','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT037','1RA AVENIDA 1-57 ZONA 1, EL PROGRESO, JUTIAPA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT038','1RA CALLE 1-A095 A PB Z. 2 MOMOSTENANGO TOTONICAPAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT039','1RA CALLE 2-07 ZONA 1 SAN JOSÉ PINULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT040','1RA CALLE 6-17 C.C. MUNDO MAYA INTERNATIONAL MALL 1ER NIVEL LOCAL 103 Z.1 SANTA ELENA FLORES, PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT041','1RA CALLE 7-27 C.C. PRADERA CHIMALTENANGO LOCAL Z.2 CHIMALTENANGO, CHIMALTENANGO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT042','1RA CALLE A 1-10 Z2, TECPAN, CHIMALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT043','1RA CALLE LOTE 11 MANZANA 1-G KM 6.5 CARRETERA A LA MAYA ZONA 18 CC PLAZA SURTI AHORROLOCAL N1L102, COLONIA LAVARREDA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT044','1RA CALLE Y 1ERA AV. 1-01 CALLE REAL, C.C.SUPER AHORRO SAN JOSE PINULA, LOCALES 3 Y 4 Z.4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT045','2 AV 5-63 Z 1, AMATILTLAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT046','20 CALLE 33-62 ZONA 7  VILLA HERMOSA SAN MIGUEL PETAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT047','20 CALLE 33-69 ZONA 7, VILLA HERMOSA, SAN MIGUEL PETAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT048','23 CALLE 1-55 C.C. PLAZA CENTRASUR KIOSKO K3  PB Z.12, VILLA NUEVA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT049','23 CALLE 1-55 ZONA 12 VILLA NUEVA CENTRO COMERCIAL CENTRA SUR KIOSKO 9PB','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT050','23 CALLE 20-24 ZONA 7 CC PACIFIC VILLA HERMOSA LOCAL 10-38','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT051','2A. AVENIDA 4-30 ZONA 1, SANTA CRUZ DEL QUICHE, QUICHE.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT052','2A. CALLE 3-23 ZONA 1, EDIFICIO VISATA HERMOSA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT053','2AV 5-060 ZONA 1, SANTA CRUZ DEL QUICHE, QUICHE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT054','2CALLE 1-22, ZONA 2 TECPAN, CHIMALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT055','2DA CALLE 0-05, ZONA 3 SANARATE EL PROGRESO SUCURSAL NO. 28','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT056','2DA. AV, 4-38, Z.1, SANTA CRUZ DEL QUICHE.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT057','3 AVENIDA 0-50 ZONA 1 LOCAL 6 STA. CATARINA PINULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT058','3 CALLE 3-12 A ZONA 7 COLONIA LANDIVAR, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT059','33 AV A 24-80 Z 7, COL. SHELL-','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT060','39 AVENIDA 9-60 ZONA 7 COLONIA EL RODEO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT061','3av. 2-63 z.4, BARRIO LA DEMOCRACIA, GUASTATOYA,  EL PROGRESO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT062','3RA 3-48 ZONA 1 TECUN UMAN, SAN MARCOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT063','3RA AV 4-45B ZONA 1 STA. LUCIA COTZ.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT064','3RA AVENIDA 6-54 BARRIO SAN ANTONIO, AMATITLAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT065','3RA. CALLE, 6-51 ZONA 1, CHIQUIMULA, CHIQUIMULA INTERIOR PAIZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT066','4 CALLE 12-46 Z.1 QUETZALTENANGO, QUETZALTENANGO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT067','4 CALLE 4-00 ZONA 1 CC. GALERIAS KAROSSI LOCAL 6-B STA ELENA FLORES PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT068','4 CALLE PONIENTE N.18 INTERIOR KODAK ANTIGUA GUATEMALA SACATEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT069','4 TA CALLE 3-32, Z2 SAN PEDRO SACATEPEQUEZ , GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT070','4 TA CALLE APTO 3-20 Z.2 SAN RAYMUNDO, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT071','4 TA. CALLE 14-72 ZONA 1 ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT072','41 AV 3-10 Z 4, C.C. PLAZA SAN NICOLAS LOC. 131','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT073','49 CALLE 21-80 Z.12 C.C. LOS CEDROS LOCAL 19, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT074','4A. CALLE 4-82, ZONA 1, VILLA NUEVA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT075','"4TA AVENIDA O-41 ZONA 2 C.C. PASEO VILLA CANALES, 1ER NIVEL LOCAL 125 VILLA CANALES, GUATEMALA"','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT076','4TA CALLE 18-01 Z.3 LOCAL 96 PRIMER NIVEL C.C. MONT BLANC, QUETZALTENANGO, QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT077','4TA CALLE Y 7MA AV. 7-24 ZONA 1, POPTUN, PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT078','5 av. 4-45 A, local 2, z.0, La Gomera, Escuintla','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT079','5 CALLE 4-14 ZONA 1, BARRIO LA BATALLA, COATEPEQUE, QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT080','5 CALLE 5-59 ZONA 1 RETALHULEU EDIFICIO MORAZAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT081','5TA AV. 2-18 Z.11 VILLA NUEVA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT082','5TA AV. 2-18 Z.2, CHIMALTENANGO, CHIMALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT083','5TA CALLE 5-47, ZONA 1 MIXCO,GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT084','5TA. CALLE 9-55 ZONA 2 CANTON MORAZAN CENTRO COMERCIAL LA TRINIDAD MALACATAN LOCAL F6-7 MALACATAN SAN MARCOS.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT085','6 AV 9-66 Z.1 GUATEMALA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT086','6 AVE 0-35 ZONA 4, CENTRO COMERCIAL PLAZA ZONA 4, PRIMER NIVEL, KIOSKO C, LOCAL 31','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT087','6 AVENIDA 9-37 ZONA 1.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT088','6A. AVENIDA 8-10, ZONA 4, SAN JUAN SACATEPEQUEZ, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT089','6AV. Y 4TA CALLE 6-00, TECULUTAN, ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT090','6ta av 12-51 c.c. 4to nivel local 401-8','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT091','6TA AV. 2-06 ZONA 1 CALZADA LAZARO  CHACON LOCAL  1 TECULUTAN  ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT092','6TA. CALLE 6-35, ZONA 1  SAN MARCOS SAN PEDRO,S.S.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT093','7 CALLE 11-85 LOCAL 3 BARRIO EL HOSPITAL, AMATITLAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT094','7 CALLE 2DA AV. 7-11 ZONA 1, LOCAL 5, 1ER NIVEL. MAZATENANGO, SUCHITEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT095','7 CALLE 30-50 MIXCO, GUATEMALA COLONIA BOSQUES DE SAN NICOLAS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT096','7A CALLE 2-02, ZONA 2, LOCAL 49 C.C. PRADERA CHIMALTENANGO ESTABLECIMIENTO NO. 24','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT097','7A. CALLE, CARRRETERA INTERAMERICANA, 1-17, ZONA1 K118, CENTRO COMERCIAL LAS PUERTAS SAN LUCAS.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT098','7A. CALLE, CARRRETERA INTERAMERICANA, 1-17, ZONA1 K3, CENTRO COMERCIAL LAS PUERTAS SAN LUCAS.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT099','7AV. 3-31 Z.1 TOTONICAPAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT100','7AV. 4-33 Z.1 SAN PEDRO CARCHA, ALTA VERAPAZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT101','7MA. CALLE 11-85 LOCAL 1 BARRIO EL HOSPITAL, AMATITLAN, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT102','8 CALLE, ENTRE 6 Y 7 AVENIDA, CASA 78, PUERTO BARRIOS.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT103','8VA AV.3-10 ZONA 1, EL ESTOR IZABAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT104','9NA CALLE 0-20 ZONA 9, QUETZALTENANGO AV. LAS AMERICAS, C.C. PASEO LAS AMERICAS LOCAL 4 Y 5','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT105','AV. LAS AMERICAS 5-88 Z.9, QUETZALTENANGO, QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT106','AV. TIOFILO SOLARES 9-15, NUEVA SANTA ROSA, SANTA ROSA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT107','AV. TIOFILO SOLARES 91-65,ZONA 1, LOCAL 16, PRIMER NIVEL,  NUEVA SANTA ROSA, SANTA ROSA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT108','AVENIDA LAS AMERICAS 7-12 ZONA 3 LOCAL 52 CC PRADERA XELA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT109','AVENIDA SIMON BOLIVAR 18000 ZONA 0, MORALES IZABAL.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT110','BARRIO EL CENTRO EL NARANJO FRONTERA, LA LIBERTAD, PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT111','BARRIO EL CENTRO RIO DULCE LIVINSTON IZABAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT112','BODEGA PLANTA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT113','BOULEVAR EL CAMINERO 14-32LOCAL 12 ZONA 6 MIXCO,GUATEMALA  CENTRO C. SAN FRANCISCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT114','BOULEVAR SAN CRISTOBAL MANZANA CC ZONA 8  SECTOR B-1 PLAZA SAN CRISTOBAL LOCAL 133-134 MIXCO GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT115','BOULEVARD EL NARANJO 12-41 ZONA 4, COLONIA EL NARANJO, FUTECA KIOSKO K-3, MIXCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT116','BOULEVARD LOS PROCERES, CENTRO COMERCIAL PRADERA, 1ER NIVEL, ZONA  10, GUATEMALA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT117','BOULEVARD SAN CRISTOBAL, LOCAL 135, SECTOR B, CENTRO COMERCIAL PLAZA SAN CRISTOBAL, MIXCO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT118','BOULEVERD EL FRUTAL 14-00 ZONA 5 C.C. EL FRUTAL 1 ER NIVEL KIOSKO 24','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT119','C.C EL FRUTAL 1ER NIVEL LOCAL 5 ZONA 5 BOULEVAR EL FRUTAL VILLA NUEVA,GUATEMALA ZONA 5','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT120','C.C. JARDINES DE SAN JUAN, ZONA 07 DE MIXCO, LOCAL 32','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT121','C.C. MEGASEIS 15 AVA 16-11 ZONA 06 LOCAL 228','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT122','C.C. MEGASEIS 15 AVA 16-11 ZONA 06 LOCAL 428','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT123','C.C. METROPLAZA MUNDO MAYA LOCAL 13 CARRETERA PRINCIPAL FRENTE AL AREOPUERTO STA ELENA FLORES PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT124','CA-9 NORTE RUTA AL ATLANTICO 40-26 ZONA 17 GRAN C.C. CENTRA NORTE KIOSKO K-7, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT125','CA-9 NORTE RUTA AL ATLANTICO 40-26 ZONA 17 GRAN C.C. CENTRA NORTE KIOSKO K-9, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT126','CA-9 NORTE RUTA AL ATLANTICO 40-26 ZONA 17 GRAN C.C. CENTRA NORTE LOCAL U-28, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT127','CA-9 NORTE RUTA AL ATLANTICO 40-26 ZONA 17 GRAN C.C. CENTRA NORTE LOCAL U-50, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT128','CALLE ASFALTADA NO. 99148PB LA LIBERTAD PETEN ZONA 0','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT129','CALLE BETHANIA B-236, FABRICA CANTEL, PASAC 1ERO, CANTEL QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT130','CALLE MUNICIPAL 86PB, BARRIO EL CENTRO SAYAXCHE PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT131','CALLE PRINCIPA, COATEPEQUE, QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT132','CALLE PRINCIPAL 9116 ZONA 0 MELCHOR DE MENCOS PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT133','CALLE PRINCIPAL HACIA LA FRONTERA EL SALVADOR LOTE NO.18 CIUDAD PEDRO DE ALVARADO JUTIAPA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT134','CALLE PRINCIPAL SANTANDER, LOCAL 1, PANAJACHEL, SOLOLA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT135','CALLE PRINCIPAL, BARRIO EL CENTRO, GUALAN, ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT136','CALLE PRINCIPAL, BARRIO VISTA HERMOSA ZONA 0, SAN LUIS PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT137','CALLE REAL 3-81 CANTON AGUA TIBIA LOCAL NO. 1, PALENCIA GUATEMALA-','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT138','CALLE REAL N. 39 ZONA 1 JOCOTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT139','CALLE RODOLFO ROBLES 16 AV. 16-03 ZONA 3 QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT140','CALZ. ATANASIO TZUL, 51-57, ZONA 12 PLAZA ATANASIO TZUL LOCAL 05 GUATEMALA,GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT141','CALZ. JOSE MILLA Y VIDAURRE 15-00 Z. 6 GUATEMALA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT142','CALZ. SAN JUAN C.C. JARDINES DE SAN JUAN, LOCAL 23.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT143','CALZ. SAN JUAN C.C. MONSERRAT LOC. 109 Z 4 de mixco.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT144','CALZ. SAN JUAN C.C. MONSERRAT LOC. 155 Z 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT145','CALZADA AGUILAR BATRES 32-10 C.C. PACIFIC CENTER LOCAL 212 Z.11','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT146','CALZADA JOSE MILLA Y VIDA URRE 16-83 ZONA 6 INTERIOR DE PAIZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT147','CALZADA KAIBIL BALAM EL CAMBOTE ZONA 11 CENTRO COMERCIAL PRADERA HUEHUETENANGO LOCAL 349  TERCER NIVEL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT148','CALZADA ROOSEVELT 22-43 ZONA 11 CENTRO COMERCIAL TIKAL FUTURA LOCAL 143-SV PRIMER NIVEL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT149','CALZADA ROOSEVELT CENTRO COMERCIAL TIKAL FUTURA, 1ER NIEVEL, 22-43 ZONA 11, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT150','CALZADA ROOSEVELT CENTRO COMERCIAL TIKAL FUTURA, 1ER NIEVEL, LOCAL 103-K5 22-43 ZONA 11, GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT151','CALZADA SAN JUAN Y 10 AV. COMPLEJO COMERCIAL METAMERCADO MIXCO SAN JUAN LOCAL 184-F Z.4 MIXCO, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT152','CALZADA SAN JUAN, CENTRO COMERCIAL LA QUINTA, LOCAL 31, 13-90 ZONA 7, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT153','"CALZADA SANTA LUCIA NORTE NUMERO CINCO ANTIGUA GUATEMALA, SACATEPEQUEZ"','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT154','CARRETERA A CHIQUIMULA K. 167.50 C.C. PRADERA CHIQUIMULA LOCAL  108 CHIQUIMULA, CHIQUIMULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT155','Carretera a San Jose Pinula 1-70 zona 1 Aldea don Justo kilometro 17.4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT156','CARRETERA AL SALVADOR KM. 21.5 PLAZA MADERO LOCAL 16 FRAIJANES, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT157','CARRETERA INTERAMERICANA K. 29.5 CRUCE A SANTIAGO C.C. MULTIPLAZA EL SAUCE LOCAL 33 SAN LUCAS SACATEPEQUEZ SACATEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT158','CARRETERA INTERAMERICANA K. 29.90 COMERCIAL PLAZA SAN LUCAs LOCAL 19 PRIMER NIVEL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT159','CARRETERA INTERAMERICANA KM.116, C.C. METROPLAZA JUTIAPA, LOCAL 112','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT160','CARRETERA KILOMETRO 29-60 CENTRO COMERCIAL PLAZA DEL LAGO AMATITLAN.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT161','CC DE LA ZONA 4 1ER NIVEL LOCAL 37.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT162','CENTRO COMERCIAL LA TRINIDAD COATEPEQUE, KIOSKO 10, ZONA 1, COATEPEQUE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT163','CENTRO COMERCIAL PRADERA XELA LOCAL 24 INTERIOR A BULOCKS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT164','CENTRO COMERCIAL UNICENTRO. 19 C 5-47 Z-10','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT165','CONECTION','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT166','CONECTION  COATEPEQUE PARQUE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT167','CONECTION  LA LIBERTAD-PETEN 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT168','CONECTION  PARROQUIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT169','CONECTION 18  CALLE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT170','CONECTION AGUILAR BATRES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT171','CONECTION AMATITLAN 1','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT172','CONECTION AMATITLAN 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT173','CONECTION AMATITLAN 3 - PUNTO NET','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT174','CONECTION AMATITLAN 7','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT175','CONECTION AMATITLAN V','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT176','CONECTION ANTIGUA 5','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT177','CONECTION ANTIGUA II','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT178','CONECTION ATANASIO TZUL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT179','CONECTION ATLANTIDA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT180','CONECTION BARBERENA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT181','CONECTION BETHANIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT182','CONECTION BOCA DEL MONTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT183','CONECTION BOCA DEL MONTE 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT184','CONECTION BOSQUEZ 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT185','CONECTION CANTEL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT186','CONECTION CAPITOL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT187','CONECTION CARCHA 2 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT188','CONECTION CENTRA NORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT189','CONECTION CENTRA NORTE 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT190','CONECTION CENTRA NORTE 5','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT191','CONECTION CENTRAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT192','CONECTION CENTRA-SUR','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT193','CONECTION CENTRO COMERCIAL ZONA 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT194','CONECTION CHIMALTENANGO 3','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT195','CONECTION CHIMALTENANGO 6 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT196','CONECTION CHIMALTENANGO 7 BY FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT197','CONECTION CHIQUIMULA 5 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT198','CONECTION CIUDAD PEDRO DE ALVARADO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT199','CONECTION CIUDAD QUETZAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT200','CONECTION CLARO METROCENTRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT201','CONECTION COATEPEQUE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT202','CONECTION CUILAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT203','CONECTION EL FARO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT204','CONECTION EL FRUTAL 1 - KIOSKO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT205','CONECTION EL FRUTAL 2 - MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT206','CONECTION EL LIMON','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT207','CONECTION EL MILAGRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT208','CONECTION EL TREBOL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT209','CONECTION ESCUINTLA  2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT210','CONECTION ESTANZUELA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT211','CONECTION ESTOR','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT212','CONECTION FLORES 3 - PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT213','CONECTION FUJI COLORAMA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT214','CONECTION FUJI ESKALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT215','CONECTION FUJI QUICHE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT216','CONECTION FUTECA MIXCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT217','CONECTION GARANTIAS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT218','CONECTION GEMINIS 10','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT219','CONECTION GUALAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT220','CONECTION GUASTATOYA EL PROGRESO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT221','CONECTION HUAWEI XELA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT222','CONECTION HUEHUETENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT223','CONECTION JALAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT224','CONECTION JOCOTALES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT225','CONECTION JOCOTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT226','CONECTION KIOSCO CENTRA NORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT227','CONECTION KIOSCO PRADERA BY FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT228','CONECTION KIOSKO COATEPEQUE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT229','CONECTION KODAK FLORIDA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT230','CONECTION KODAK METRONORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT231','CONECTION LA FLORIDA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT232','CONECTION LA GOMERA 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT233','CONECTION LA QUINTA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT234','CONECTION LAS CRUCES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT235','CONECTION LIQUIDACION','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT236','CONECTION LOS CEDROS 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT237','CONECTION MALACATAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT238','CONECTION MAZATENANGO 3 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT239','CONECTION MEGA BOSQUES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT240','CONECTION MEGA SEIS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT241','CONECTION MEGA SEIS 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT242','CONECTION MELCHOR DE MENCOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT243','CONECTION META TERMINAL QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT244','CONECTION METAMERCADO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT245','CONECTION METATERMINAL DEL NORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT246','CONECTION METROCENTRO 1 MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT247','CONECTION METROCENTRO 3','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT248','CONECTION METROCENTRO HUAWEI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT249','CONECTION METRONORTE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT250','CONECTION METRONORTE HUAWEI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT251','CONECTION METROPLAZA JUTIAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT252','CONECTION MINERVA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT253','CONECTION MIXCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT254','CONECTION MIXCO 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT255','CONECTION MOMOSTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT256','CONECTION MONTSERRAT 1','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT257','CONECTION MONTSERRAT 2 - MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT258','CONECTION MONTUFAR','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT259','CONECTION MORALES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT260','CONECTION NUEVA SANTA ROSA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT261','CONECTION PACIFIC CENTER','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT262','CONECTION PACIFIC VILLA HERMOSA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT263','CONECTION PAIZ PARROQUIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT264','CONECTION PAIZ PRADERA CHIQUIMULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT265','CONECTION PAIZ PUERTA DEL SOL-C.C. Z.4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT266','CONECTION PALENCIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT267','CONECTION PALIN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT268','CONECTION PANAJACHEL  BY FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT269','CONECTION PASEO AMERICAS XELA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT270','CONECTION PASIFIC TECULUTAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT271','CONECTION PETEN EL CHAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT272','CONECTION PETEN EL NARANJO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT273','CONECTION PLAZA MADERO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT274','CONECTION PLAZA MADERO  ROOSBELT','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT275','CONECTION PLAZA MADERO ATANACIO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT276','CONECTION PLAZA PINULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT277','CONECTION POCTUN PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT278','CONECTION PRADERA CHIMALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT279','CONECTION PRADERA CHIQUIMULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT280','CONECTION PRODUCTO DEFECTUOSO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT281','CONECTION PROGRESO JUTIAPA 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT282','CONECTION PUERTO BARRIOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT283','CONECTION QUICHE BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT284','CONECTION RETALHULEU  3','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT285','CONECTION RETALHULEU TRINIDAD','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT286','CONECTION REU C.C. TRINIDAD BY QUIK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT287','CONECTION RIO DULCE 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT288','CONECTION SALAMA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT289','CONECTION SAN CRISTOBAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT290','CONECTION SAN CRISTOBAL  FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT291','CONECTION SAN FRANCISCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT292','CONECTION SAN JOSE PINULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT293','CONECTION SAN JOSE PINULA 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT294','CONECTION SAN JOSE PINULA BY FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT295','CONECTION SAN JUAN SACATEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT296','CONECTION SAN LUCAS 1 LAS PUERTAS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT297','CONECTION SAN LUCAS 2 LAS PUERTAS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT298','CONECTION SAN LUCAS 3','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT299','CONECTION SAN LUIS PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT300','CONECTION SAN MIGUEL PETAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT301','CONECTION SAN PEDRO SACATEPEQUEZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT302','CONECTION SAN PEDRO SAN MARCOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT303','CONECTION SAN RAYMUNDO BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT304','CONECTION SANARATE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT305','CONECTION SANTA CATARINA PINULA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT306','CONECTION SANTA CLARA - KIOSKO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT307','CONECTION SANTA CLARA - MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT308','CONECTION SANTA CLARA 3','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT309','CONECTION SANTA ELENA - FLORES 1 - PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT310','CONECTION SANTA ELENA - FLORES 2 - PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT311','CONECTION SANTA LUCIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT312','CONECTION SANTA LUCIA BY FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT313','CONECTION SANTA ROSA 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT314','CONECTION SAYAXCHE - PETEN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT315','CONECTION SIQUINALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT316','CONECTION SUMPANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT317','CONECTION TECPAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT318','CONECTION TECPAN 2 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT319','CONECTION TECULUTAN 2 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT320','CONECTION TECUN  UMAN BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT321','CONECTION TIKAL FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT322','CONECTION TIKAL FUTURA 2 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT323','CONECTION TIKAL FUTURA HUAWEI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT324','CONECTION TOTONICAPAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT325','CONECTION UNICENTRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT326','CONECTION VILLA CANALES','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT327','CONECTION VILLA HERMOSA 2 - MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT328','CONECTION VILLA HERMOSA I','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT329','CONECTION VILLA NUEVA 1','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT330','CONECTION VILLA NUEVA 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT331','CONECTION XELA 1 - MEGA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT332','CONECTION XELA FUJI','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT333','CONECTION XELA LA DEMOCRACIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT334','CONECTION XELA MONTBLANC 2 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT335','CONECTION ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT336','CONECTION ZONA 1','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT337','CONECTION ZONA 1 PNC','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT338','CONECTION ZONA 15','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT339','CONECTION ZONA 6 BY QUICK','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT340','CRT. AL ATLANTICO C.C. PLAZA SAN RAFAEL LOCAL 36','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT341','DIAGONAL 3 CALZADA ATANASIO TZUL, 17-13, Z.12, LOCAL 22, GUATEMALA,','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT342','FRENTE AL PARQUE, CALLE PRINCIPAL , COATEPEQUE, QUETZALTENANGO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT343','FUJI QUICHE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT344','INGEPROSA AMATITLAN 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT345','INGEPROSA CENTRA SUR DOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT346','INGEPROSA CENTRAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT347','INGEPROSA CHIQUIMULIA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT348','INGEPROSA COBAN DOS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT349','INGEPROSA INNOVATION  FRUTAL','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT350','INGEPROSA PAIZ  COBAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT351','INGEPROSA PAIZ AMERICAS','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT352','INGEPROSA PAIZ MEGACENTRO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT353','INGEPROSA PAIZ MONT BLANC','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT354','INGEPROSA PRADERA XELA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT355','INGEPROSA RETALHULEU','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT356','INGEPROSA RIO DULCE 1','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT357','INGEPROSA SAN LUCAS - KIOSKO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT358','INGEPROSA SAN RAFAEL 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT359','INGEPROSA TECULUTAN','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT360','INGEPROSA TIQUISATE','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT361','INGEPROSA VILLA CANALES 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT362','KILOMETRO 13.7 CALZADA ROOSEVELT ZONA 3 CENTRO COMERCIAL ESKALA ROSSEVELT LOCAL 108 MIXCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT363','Kilometro 89.5 Carretera a Mazatenango Santa Lucia Cotzumalguapa, Escuintla','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT364','KIOSKO PLAZA ZONA 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT365','KM 123.5 C.C. PACIFIC TECULUTAN  LOCAL 4','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT366','KM 17.9 CARR A SAN JOSE PINULA, C.C. EL FARO LOC. 74','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT367','KM 292.5 C.C. LA PRADERA, PUERTO BARRIOS, LOCAL 40, PUERTO BARRIOS IZABAL.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT368','KM 54.5 SANTA VICTORIA, BARBERENA STA ROSA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT369','KM. 17.5 CARR CA-9 AL PACIFICO C.C. SANTA CLARA,  KIOSKO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT370','KM. 17.5 CARR CA-9 AL PACIFICO C.C. SANTA CLARA, LOC. 141','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT371','KM140.5 CARRETERA CA-10A ZACAPA C.C.MEGAPLAZA LOCAL LC23, ESTANZUELA, ZACAPA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT372','KM5 CARRETERA AL ATLANTICO ZONA 17 C.C METRO NORTE kiosko 420','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT373','KM5 CARRETERA AL ATLANTICO ZONA 17 C.C METRO NORTE LOCAL 10','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT374','KM5 CARRETERA AL ATLANTICO ZONA 17 C.C METRO NORTE LOCAL 17','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT375','LOCAL ANCLA NO. 1 C.C. MEGACENTRO, CALZADA ROOSEVELT 29-60 ZONA 7 GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT376','LOCAL ANCLA NO. 1 C.C. MONT BLANC ENTRE 18 Y 19 AVENIDA ENTE 3A. Y 4A. CALLES, ZONA 3 QUETZALTENANGO.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT377','LOCAL ANCLA NO. 1 C.C. PLAZA GALA, 11 CALLE ENTRE AVENIDA LAS AMÉRICAS Y 15 AVENIDA ZONA 13 GUATEMALA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT378','LOCAL NO. 52 (ANCLA NO. 1) C.C. MAGDALENA 1A CALLE 15-12, ZONA 2, COBÁN, ALTA VERAPAZ','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT379','LOTE 13 , MANZ G SEC. 3A. COL. EL EDEN CIUDAD QUETZAL, PLAZA DORADA,SAN JUAN SACATEPEQUEZ,GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT380','LT. 223 SEC. H Z 6 COL. EL MILAGRO-','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT381','MANZANA 29, LOTE 13, APARTAMENTO C, ZONA 11, JARDINES DE MINERVA 2, MIXCO','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT382','MERCADO LA PARROQUIA ZONA 6 LOCAL 6-28 GUATEMALA, GUATEMALA.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT383','NIVEL PRINCIPAL  KIOSKO 103, C.C. SANTA  CLARA, KM 17.5 CARRETERA AL PACIFICO, BARCENA, VILLA NUEVA, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT384','PLAZA MADERO ROOSEVELT KM 13.5 CALZADA ROOSEVELT 7-59, Z.3, COLONIA COTIO, MIXCO, GUATEMALA','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT385','PUERTO BARRIOS 2','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT386','RUTA 4, 4-71 ZONA 1 LOCAL 2-A  C.C. PLAZA TECULUTAN BARRIO II CENTRO SALAMA BAJA VERAPAZ ESTABLECIMIENTO NO. 23','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT387','ZONA 0 MERCADO RIO DULCE 8025, LIVINSTON, IZABAL.','5', NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('CNC-GT388','ZONA 1, EL CHAL, PETEN','5', NOW(), NOW(), NULL);
