INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN001','CEDI',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN002','CEDI KENNEDY',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN003','CEDI KENNEDY2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN004','CEDI2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN005','LL CASCADAS',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN006','LL CASCADAS2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN007','LL CITY MALL SPS',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN008','LL CITY MALL SPS2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN009','LL CITY MALL TGU',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN010','LL CITY MALL TGU2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN011','LL EXPRES CEIBA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN012','LL EXPRES CEIBA MEGAPLAZA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN013','LL EXPRES CEIBA MEGAPLAZA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN014','LL EXPRES CEIBA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN015','LL EXPRES CHOLOMA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN016','LL EXPRES CHOLOMA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN017','LL EXPRES CHOLUTECA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN018','LL EXPRES CHOLUTECA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN019','LL EXPRES COMAYAGUA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN020','LL EXPRES COMAYAGUA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN021','LL EXPRES CORTES',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN022','LL EXPRES CORTES2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN023','LL EXPRES KENNEDY',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN024','LL EXPRES KENNEDY2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN025','LL EXPRES PROGRESO',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN026','LL EXPRES PROGRESO2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN027','LL EXPRES ROATAN',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN028','LL EXPRES ROATAN2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN029','LL EXPRES SPS',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN030','LL EXPRES SPS2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN031','LL EXPRES TGU',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN032','LL EXPRES TGU2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN033','LL EXPRES TOCOA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN034','LL EXPRES TOCOA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN035','LL EXPRES VILLANUEVA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN036','LL EXPRES VILLANUEVA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN037','LL EXPRESS ENTRADA COPAN',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN038','LL EXPRESS ENTRADA COPAN2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN039','LL MEGAPLAZA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN040','LL MEGAPLAZA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN041','LL MULTIPLAZA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN042','LL MULTIPLAZA2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN043','LL PEATONAL SPS',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN044','LL PEATONAL SPS2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN045','LL PEATONAL TGU',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN046','LL PEATONAL TGU2',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN047','TECNO ALAMEDA',11,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('LDY-HN048','TECNO ALAMEDA2',11,NOW(), NOW(), NULL);
