INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN001','Bodega Central Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN002','Inventario',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN003','Kiosco FD Mega Plaza Progreso',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN004','Kiosco PT City Mall Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN005','Kiosco PT La Colonia #1 Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN006','Kiosco PT La Colonia Villas del Sol',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN007','Kiosco PT Mall El Dorado Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN008','Kiosco PT Mall Las Cascadas',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN009','Kiosco PT Mall Las Cascadas 2',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN010','Kiosco PT Mall Premier Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN011','Kiosco PT Metromall',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN012','Kiosco PT Miraflores',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN013','Kiosco PT Monjaras Choluteca',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN014','Kiosco PT Multiplaza Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN015','Kiosco PT Novacentro',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN016','Kiosco PT Pasaje Valle SPS',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN017','Kiosco PT Unimall Choluteca',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN018','Kiosco TN Altara San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN019','Kiosco TN Catacamas',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN020','Kiosco TN Centro de Servicio La Ceiba',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN021','Kiosco TN Centro de Servicio Tecnico SPS',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN022','Kiosco TN Centro San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN023','Kiosco TN Choloma',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN024','Kiosco TN Circunvalacion San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN025','Kiosco TN City Mall San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN026','Kiosco TN City Mall Tegucigalpa',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN027','Kiosco TN Comayagua',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN028','Kiosco TN El Progreso',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN029','Kiosco TN La Republica La Ceiba',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN030','Kiosco TN Mall Cascadas',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN031','Kiosco TN Megaplaza San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN032','Kiosco TN Metro Mall',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN033','Kiosco TN Miraflores',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN034','Kiosco TN Multiplaza Tegucigalpa',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN035','Kiosco TN Novacentro',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN036','Kiosco TN Puerto Cortes',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN037','Kiosco TN Roatan',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN038','Kiosco TN San Lorenzo',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN039','Kiosco TN Santa Monica San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN040','Kiosco TN Santa Rosa de Copan',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN041','Kiosco TN Siguatepeque',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN042','Kiosco TN Tela',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN043','Kiosco TN Tocoa',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN044','Kiosco TN Toronjal',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN045','Kiosco TN Unimall Choluteca',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN046','Kiosco TN Uniplaza Danli',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN047','Kiosco TN Uniplaza Juticalpa',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN048','Kiosco TN Villanueva',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN049','Tienda Altara San Pedro Sula',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN050','Tienda Boulevard',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN051','Tienda Catedral',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN052','Tienda Central',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN053','Tienda Choloma',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN054','Tienda Choluteca',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN055','Tienda City Mall SPS',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN056','Tienda City Mall Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN057','Tienda Comayagua',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN058','Tienda Comayagua Centro',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN059','Tienda El Progreso',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN060','Tienda El Progreso Centro',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN061','Tienda FD Mall Cascadas',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN062','Tienda Galerias Del Valle',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN063','Tienda Juticalpa',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN064','Tienda La Ceiba',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN065','Tienda Mall Las Cascadas',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN066','Tienda Metro Mall',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN067','Tienda Miraflores',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN068','Tienda Multiplaza SPS',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN069','Tienda Multiplaza Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN070','Tienda Próceres SPS',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN071','Tienda PT Midence Soto',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN072','Tienda Puerto Cortes',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN073','Tienda Santa Rosa Copán',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN074','Tienda Soluciones Digitales Teg',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN075','Tienda Unimall Choluteca',13,NOW(), NOW(), NULL);
INSERT INTO puntosventas (codigo, nombre, idsucursal, created_at, updated_at, deleted_at) values('JS-HN076','Tienda Uniplaza Danli',13,NOW(), NOW(), NULL);
